const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category: 'Shirt',
            image:'../images/p1.jpg',
            price:150,
            countInStock: 10,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirt',
            category: 'Shirt',
            image:'../images/p2.jpg',
            price:200,
            countInStock: 20,
            brand:'Adidas',
            rating: 4.5,
            numReviews: 11,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lee Free Shirt',
            category: 'Shirt',
            image:'../images/p3.jpg',
            price:340,
            countInStock: 0,
            brand:'Lee',
            rating: 4.8,
            numReviews: 15,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            category: 'Pant',
            image:'../images/p4.jpg',
            price:120,
            countInStock: 50,
            brand:'Nike',
            rating: 4.5,
            numReviews: 14,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Nike Slim Pant',
            category: 'Pant',
            image:'../images/p5.jpg',
            price:149,
            countInStock: 55,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        }, 
        {
            _id:'6',
            name:'Nike Fitting Pant',
            category: 'Shirt',
            image:'../images/p6.jpg',
            price:199,
            countInStock: 40,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'7',
            name:'Stylish Dress',
            category: 'Dress',
            image:'../images/dress1.jpg',
            price:344,
            countInStock: 10,
            brand:'Stylish',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
        {
            _id:'8',
            name:'Modern Dress',
            category: 'Dress',
            image:'../images/dress3.jpg',
            price:231,
            countInStock: 100,
            brand:'Nike',
            rating: 4.5,
            numReviews: 10,
            description:'high quality product',
        },
    ],
};
export default data;